### ISSUE TITLE
ERROR]: Could not pass event PlayerDeathEvent to BloodMoney v1.1.0

### ISSUE THREAD

**Issue by AvatarAcid** [TheReturningVoid/bloodmoney#1]
Hi JjStAr992_Gaming,

Just would like to bring this to your attention. This is creating a lot of noise on our server and making logging increasingly difficult.

When a player dies from any means other than from PvP by another human player, BloodMoney errors occur.

GitHub will not let me attach files in here, so I'm not sure how to do this in a decent manner. But I will paste one in here at the bottom.

Thanks,
AA

[20:01:23 ERROR]: Could not pass event PlayerDeathEvent to BloodMoney v1.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:395) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:206) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:247) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1448) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:173) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:285) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:382) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-76236cb-62a2169]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-76236cb-62a2169]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
Caused by: java.lang.NullPointerException
        at net.milkbowl.vault.permission.Permission.has(Permission.java:98) ~[?:?]
        at net.thereturningvoid.bloodmoney.listeners.PlayerDeathListener.onKillPlayer(PlayerDeathListener.java:40) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-76236cb-62a2169]
        ... 25 more
[20:01:23 INFO]: pwnmusic drowned

Here is a PvP Kill:
[20:00:06 INFO]: [Bounty] 0.0
[20:00:06 INFO]: pwnmusic was slain by AvatarAcid

**Comment by TheReturningVoid** [comment]
Oh dear... :P

Working on it right now.

**Comment by AvatarAcid** [comment]
Ok thanks! If you need any more examples or testing, just let me know.

**Comment by TheReturningVoid** [comment]
There we go. That was a quick one :P Forgot to check if the player was actually killed by a player, and Vault tripped up on getting permissions from a non-existent player (obviously). Version v1.1.1 will be available on BukkitDev as soon as it gets approved (about 5-15 mins).

**Comment by AvatarAcid** [comment]
Thanks!

**Comment by TheReturningVoid** [comment]
Out of curiosity, what is your server called? I'd like to see how servers are using my plugin ;)

**Comment by AvatarAcid** [comment]
Let me get back to you, I am on a private server atm testing all systems with 10 people. I'm not sure how many we can pull yet!

**Comment by TheReturningVoid** [comment]
Ok, cool.
